name: DocFX

on:
  push:
    paths-ignore: 
      - 'docs/**'
    branches:
      - master

jobs:
  docfx:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_DOCFX: ${{ secrets.GITHUB_DOCFX }}
    runs-on: windows-latest

    steps:
    - run: git config --global user.name ${env:GITHUB_ACTOR}
    - run: git config --global user.email ${env:GITHUB_ACTOR}@users.noreply.github.com

    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Build with dotnet
      run: dotnet build ./src/ClashOfClans/ClashOfClans.csproj

    - name: Setup DocFX
      run: choco install docfx

    - name: Build with DocFX
      run: |
        Remove-Item ./docs/ -Recurse
        docfx

    - name: Update GitHub Pages
      run: |
        git commit -am "Update GitHub Pages"
        git remote set-url origin https://${env:GITHUB_ACTOR}:${env:GITHUB_DOCFX}@github.com/tparviainen/clashofclans.git
        git push
